Feature/sprint ioda converters fcvdb (#848)
* Update the src/land/ascat_ssm2ioda.py converters and the corresponding ctest
output file test/testoutput/ascat_ssm.nc to the latest IODA conventions as of
2022/03/09.
Two errors remain in the ioda-validate.x tests:
 ERROR: Variable 'MetaData/datetime' needs units, but the 'units' attribute does not exist in the file.
 ERROR: Variable 'PreQC/soilMoistureNormalized' needs units, but the 'units' attribute does not exist in the file.
And one warning:
  Warning: Variable 'MetaData/datetime' uses a superseded name. Replace with 'dateTime'
Those will be addressed in a coming PR that will change the ioda-validate executable.

* Restart CI

* finish updating for JEDI data conventions

* needed to add in dateTime units

* update test ref file with units of dateTime

* fix test ref file

* trigger build

* adjust platform and sensor global attrs

* revert back to the global attributes of sensor and platform

* fix a couple coding norm problems

Co-authored-by: Ryan Honeyager <honeyage@ucar.edu>
Co-authored-by: gthompsnJCSDA <gthompsn@ucar.edu>
Co-authored-by: Fabio L R Diniz <fabiolrdiniz@gmail.com>
Co-authored-by: Fabio L R Diniz <45880035+fabiolrdiniz@users.noreply.github.com>